config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
      resources :comments, only: :create
      resources :photos, only: :create
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email


  RATINGS = {
    'one star': '1_star',
    'two stars': '2_stars',
    'three stars': '3_stars',
    'four stars': '4_stars',
    'five stars': '5_stars'
  }
  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
      NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :place
  mount_uploader :picture, PictureUploader
  
  validates :picture, presence: true
  validates :caption, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos 

  geocoded_by :address
  after_validation :geocode
  validates :name, presence: true, length: { minimum: 3, too_short: "must be longer than %{count} characters." }
  validates :address, :description, presence: true
  
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :places
has_many :comments
has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
before_action :authenticate_user!

def create
  @place = Place.find(params[:place_id])
  @place.photos.create(photo_params)
    redirect_to place_path(@place)  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all 
  end

  def new
    @place = Place.new
  end

  def create
  @place = current_user.places.new(allowed_params)
  if @place.save
    redirect_to root_path
  else
    render :new, status: :unprocessable_entity
  end
end 
 
def allowed_params
    params.require(:place).permit(:name, :address, :description)
end 

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def update
     @place = Place.find(params[:id])
    if @place.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
    end
    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
  end
end



def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end
    @place.destroy
    redirect_to root_path
end

def edit
    @place = Place.find(params[:id])
    if @place.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end

def address
    @address = Place.find(params[:id])
    if @place.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end
    @place.address
    redirect_to root_path
end

def description
    @description = Place.find(params[:id])
    if @place.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end
    @place.description
    redirect_to root_path
end

def name
    @name = Place.find(params[:id])
    if @place.user != current_user
    return render plain: 'Not Allowed', status: :forbidden, length: { maximum: 140, minimum: 3 }
  end
    @place.name
    redirect_to root_path
end


  private

  def place_params
    params.require(:place).permit(:name, :description, :address, :picture)
  end


end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <nav class="navbar navbar-toggleable-md navbar bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
  
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <%= link_to new_place_path, class: 'nav-text' do %>
          <i class="fa fa-plus-circle"></i>
          New Place
        <% end %>
      </li>
    </ul>

     <ul class="navbar-nav">
        <% if user_signed_in? %>
         <li class="nav-item">
         <%= link_to 'My Profile', user_path(current_user), class: 'nav-text' %>
         </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-text' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'No user is signed in :(', '#', class: 'nav-text' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
     <% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
       <div class="carousel-item active">
           <%= image_tag 'slider1.JPG', class: 'd-block img-fluid' %>
          <div class="carousel-caption d-none d-md-block">
          <h3>Find the best gluten and dairy-free spots in the Springs</h3>
    </div> 
  </div>
  <div class="carousel-item">
        <%= image_tag 'slider2.JPG', class: 'd-block img-fluid' %>
    <div class="carousel-caption d-none d-md-block">
        <h3>Grass-fed, local, gluten free burgers</h3>
    </div>
</div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="   prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
     <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="  next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
<br/>
<div class="row">
<% @places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>

    <% if place.comments.present? %>
    <div class="col-12">
  <blockquote>
    <% if place.comments.last.humanized_rating.present? %>
      <b><%= place.comments.last.humanized_rating %></b> -
    <% end %>
    <%= place.comments.last.message %>
    <small><%= place.comments.last.user.email %></small>
  </blockquote>
</div>
<% end %>
<% if place.photos.present? %>
  <div class="col-6 offset-3">
    <blockquote>
    <% if place.photos.last.picture.present? %>
    <%= link_to image_tag(place.photos.last.picture.url, class: 'img-thumbnail') %>
    <% end %>
    <%= place.photos.last.caption %>
    </blockquote>
  </div>
  <% end %> 

  </div>
<% end %>
</div>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Enter Your Place Details</h1>
 <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
<h1><%= @place.name %></h1>
<i><%= @place.address %></i>
<br/><br/>
<p><%= @place.description %></p> 

<% if @place.latitude.present? && @place.longitude.present? %>

  <script>

    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }

  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCnnghZeaq9QTit3fIQBeWY71e3Jg7Smho&callback=initMap">
  </script>

  <div id="map">
    Map goes here
  </div>
<% end %>

<br />
<!--Map Buttons-->
<div class="float-right">
  <% if current_user && current_user == @place.user %>
    <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
     <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
     <% end %>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
  <%= f.input :message %>
  <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
  <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
<% end %>
       </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

               <!-- Comment Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Add a comment
</button> 
       <!-- Photo button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#photoModal">
  Add a Photo
</button>

<!--Photo Modal -->
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="photoModal">Add a Photo</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
     <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :picture %>
          <%= f.input :caption %>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
        </div>
      <% end %>
  </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!--Added Photo-->
<div class="clear"><br /></div>
<div class="row col-10 offset-1">
<% @place.photos.each do |photo| %>
  <div class="img col-10 offset-1">
      <%= image_tag photo.picture.url, class: 'img-thumbnail' %>
    <blockquote>
      <%= photo.caption %>
    </blockquote>
  </div>
</div>
<% end %>
</div>


            
  

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="row">
    <div class="col-4">
  <%= image_tag 'user.png' %>
</div>

<div class="col-8">
<h1><%= @user.email %></h1>
<h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
<h4><%= @user.comments.count %> total comments</h4>
<h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4> 
</div>
</div>
<div class="clear"></div>
</div>
 <br /><br />
<h1 class="text-center">My Comments</h1> 
<br /><br />
<div class="row">
<% @user.comments.each do |comment| %>
<div class="col-12 col-sm-6">
  <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>
</div>
<div class="clear"></div>
<br /><br />
<h2 class="text-center">My Places</h2>
<br /><br />
<% @user.places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br />
    <p><%= place.description %></p><br />
    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>
    <% if place.comments.present? %>
      <div class="col-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
  <% end %>